// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSavedSession() {
  return window['go']['main']['App']['CheckSavedSession']();
}

export function ConnectToVPN(arg1, arg2) {
  return window['go']['main']['App']['ConnectToVPN'](arg1, arg2);
}

export function DisconnectVPN() {
  return window['go']['main']['App']['DisconnectVPN']();
}

export function GenerateConfig(arg1, arg2) {
  return window['go']['main']['App']['GenerateConfig'](arg1, arg2);
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAllSessions() {
  return window['go']['main']['App']['GetAllSessions']();
}

export function GetBestNode() {
  return window['go']['main']['App']['GetBestNode']();
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetNode(arg1) {
  return window['go']['main']['App']['GetNode'](arg1);
}

export function GetNodes(arg1, arg2) {
  return window['go']['main']['App']['GetNodes'](arg1, arg2);
}

export function GetUserProfile() {
  return window['go']['main']['App']['GetUserProfile']();
}

export function GetUserStats() {
  return window['go']['main']['App']['GetUserStats']();
}

export function GetVPNStats() {
  return window['go']['main']['App']['GetVPNStats']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SetAPIURL(arg1) {
  return window['go']['main']['App']['SetAPIURL'](arg1);
}
