// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckSavedSession():Promise<Record<string, any>>;

export function ConnectToVPN(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DisconnectVPN():Promise<void>;

export function GenerateConfig(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetAPIURL():Promise<string>;

export function GetAllSessions():Promise<Array<models.Session>>;

export function GetBestNode():Promise<models.VPNNode>;

export function GetCurrentSession():Promise<models.Session>;

export function GetCurrentUser():Promise<models.User>;

export function GetNode(arg1:string):Promise<models.VPNNode>;

export function GetNodes(arg1:string,arg2:string):Promise<Array<models.VPNNode>>;

export function GetUserProfile():Promise<models.User>;

export function GetUserStats():Promise<Record<string, any>>;

export function GetVPNStats():Promise<Record<string, any>>;

export function IsConnected():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SetAPIURL(arg1:string):Promise<void>;
